# Runs the rust linter (clippy) on your repo
#
# Parameters
#   rust: <string> = "stable"
#     Which version of rust to install when running clippy
#   args: <string> = "--all"
#     List of args to pass to clippy, defaulting to "--all"
#   allow_fail: <bool> = false
#     Ignore a failed linting
#       Useful if you want to check if your code is pristine,
#       but don't want your build to fail if its not. Also useful
#       when linting on nightly as clippy breaks often on nightly builds


parameters:
  rust: stable
  args: '--all'
  allow_fail: false

jobs:
- job: ${{ parameters.name }}
  ${{ if eq(parameters.rust, 'stable') }}:
    displayName: cargo clippy
  ${{ if ne(parameters.rust, 'stable') }}:
    displayName: cargo +${{ parameters.rust }} clippy
  continueOnError: ${{ parameters.allow_fail }}
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: internal/install.yml
      parameters:
        rust: ${{ parameters.rust }}
        components:
          - clippy
    - script: cargo clippy ${{ parameters.args }}
      displayName: Run cargo clippy